name: Deploy Dust Blog

on:
  push:
    branches:
      - main # 只有在 main 分支有推送时才触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. 安装 Node.js (针对你的 Vue 3 环境)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. 安装依赖并构建
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 4. 部署到服务器 (使用 SCP)
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          password: ${{ secrets.SERVER_SSH_KEY }}          
          source: "dist/" # Vue 构建后的目录
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          target: "/home/dust/app/ether-log-web" # 文件存放目录git
          